---
dist: bionic

language: python

before_install:
  - pyenv install -s
  - pip install -r requirements.txt
install: buildout
script: bin/test

notifications:
  email:
    on_success: never
    on_failure: never
